services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/esamiDB
      - JWT_SECRET=supersecretkey
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - backend

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: